{
 "title": "Cosmos Validator",
 "description": "It uses https://github.com/QuokkaStake/cosmos-validators-exporter and the built-in Prometheus agent. Check our Github https://github.com/htwtech/cosmos-monitoring for more info. \n",
 "tags": [
  "Validator",
  "Cosmos"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(cometbft_blocksync_syncing,job)"
    }
   },
   { "name": "chain_id", "label": "Chain ID", "query": { "query": "label_values(chain_id)" } },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values({job=\"$job\", chain_id=\"$chain_id\"},host)"
    }
   },
   {
    "name": "chain",
    "label": "Chain",
    "query": {
     "query": "label_values({chain_id=\"$chain_id\"},chain)"
    }
   },
   {
    "name": "instance",
    "label": "Node",
    "query": {
     "query": "label_values({chain_id=\"$chain_id\", host=\"$host\", job=\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"display: flex; align-items: flex-start; gap: 12px;\">\r\n  <img \r\n    src=\"https://brand-kit.htw.tech/logo/logo_solana_style_64x64.png\"\r\n    style=\"height: 60px; width: auto; align-self: flex-start; margin-top: 0px;\">\r\n\r\n  <div style=\"flex: 1;\">\r\n    <div>\r\n      <b>Independence is in the code. Strength is in the consensus. Reliability is in our nodes.</b>\r\n      <p style=\"margin: 2px 0;\">\r\n        This dashboard can help you run a Cosmos fork validator. Please check our <a href=\"https://github.com/htwtech/cosmos-monitoring\" target=\"_blank\">GitHub\r\n        </a>. You are free to change this dashboard as you wish.\r\n      </p>\r\n    </div>\r\n    <div style=\"text-align: right;\">\r\n      Best regards, <a href=\"https://htw.tech/\" target=\"_blank\">Hightower team</a>.\r\n    </div>\r\n  </div>\r\n</div>\r\n\r\n"
   }
  },
  { "title": "Brief details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Syncing Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_blocksync_syncing{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "State",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cosmos_validators_exporter_active{chain=\"$chain\",host=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jailed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cosmos_validators_exporter_jailed{chain=\"$chain\",host=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "100 - $A / $B * 100", "type": "math" }
   ]
  },
  {
   "title": "Missed Blocks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cosmos_validators_exporter_missed_blocks{chain=\"$chain\",host=\"$host\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Delegations",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cosmos_validators_exporter_delegations_count{chain=\"$chain\",host=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Delegated",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cosmos_validators_exporter_total_delegations{chain=\"$chain\",host=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consensus Validators",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_validators{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rank",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cosmos_validators_exporter_rank{chain=\"$chain\",host=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Commission %",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cosmos_validators_exporter_commission{chain=\"$chain\",host=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Сommission Unclaimed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cosmos_validators_exporter_unclaimed_commission{chain=\"$chain\",host=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rewards Self Delegation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cosmos_validators_exporter_self_delegation_rewards{chain=\"$chain\",host=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_latest_block_height{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Signed Height",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_validator_last_signed_height{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sys Load",
   "type": "stat",
   "description": "System load over all CPU cores together",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(node_load1{host=\"$host\"}) * 100 / count(count(node_cpu_seconds_total{host=\"$host\"}) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Load 1m",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(node_load1{host=\"$host\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IOWait",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_pressure_io_waiting_seconds_total{host=\"$host\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", host=\"$host\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{host=\"$host\"} / node_memory_MemTotal_bytes{host=\"$host\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{host=\"${host}\"} - node_boot_time_seconds{host=\"${host}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "cosmos_validators_exporter_chain_info{chain=\"$chain\",host=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Validator Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Total Delegated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "cosmos_validators_exporter_total_delegations{chain=\"$chain\",host=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator Acive Rate",
   "type": "timeseries",
   "description": "Measures the percentage of blocks where the validator participated successfully without missing any proposals.\nThis metric offers a clear view of the validator’s reliability and effectiveness in the consensus process. A high percentage reflects consistent and dependable performance, while a lower rate may indicate issues such as network instability or resource constraints. Tracking this metric is essential for maintaining validator efficiency and ensuring the overall health of the network",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "100-sum(cosmos_validators_exporter_missed_blocks{chain=\"$chain\",host=\"$host\"}) / sum(cosmos_validators_exporter_missed_blocks_window{chain=\"$chain\",host=\"$host\"}) *100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Delegations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "cosmos_validators_exporter_delegations_count{chain=\"$chain\",host=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator Missed Blocks Per Window",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "cosmos_validators_exporter_missed_blocks{chain=\"$chain\",host=\"$host\"}",
     "legendFormat": "Missed blocks"
    },
    {
     "expr": "sum(cosmos_validators_exporter_missed_blocks_window{chain=\"$chain\",host=\"$host\"})",
     "legendFormat": "window"
    }
   ]
  },
  {
   "title": "Self delegated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "cosmos_validators_exporter_self_delegated{chain=\"$chain\",host=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proposal Receive Rate",
   "type": "timeseries",
   "description": "Monitors how frequently the node receives block proposals within a specified time interval.\nThis metric helps assess the node’s participation in the consensus process. A consistent rate suggests stable network conditions and proper synchronization, while drops may point to connectivity issues or lags in syncing. Sudden spikes could indicate abnormal or unexpected network activity. Regularly tracking this metric is important for ensuring efficient block propagation and maintaining consensus stability.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(cometbft_consensus_proposal_receive_count{chain_id=\"$chain_id\", host=\"$host\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unclaimed commission",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "cosmos_validators_exporter_unclaimed_commission{chain=\"$chain\",host=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P2P Bytes per Sec",
   "type": "timeseries",
   "description": "The total rate of incoming P2P messages in bytes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(cometbft_p2p_message_receive_bytes_total{chain_id=\"$chain_id\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Recieve"
    },
    {
     "expr": "sum(rate(cometbft_p2p_message_send_bytes_total{chain_id=\"$chain_id\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Send"
    }
   ]
  },
  {
   "title": "Self Delegation Rewards",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "cosmos_validators_exporter_self_delegation_rewards{chain=\"$chain\",host=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Processing Time",
   "type": "timeseries",
   "description": "The average duration the node takes to process blocks over the past minute.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(cometbft_state_block_processing_time_sum{chain_id=\"$chain_id\", instance=\"$instance\"}[1m])) / sum(rate(cometbft_state_block_processing_time_count{chain_id=\"$chain_id\", instance=\"$instance\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unbonds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "cosmos_validators_exporter_unbonds_count{chain=\"$chain\",host=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P2P Message Receive Rate",
   "type": "timeseries",
   "description": "The rate of incoming P2P messages in bytes per second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (message_type) (rate(cometbft_p2p_message_receive_bytes_total{chain_id=\"$chain_id\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vaildator Voting Power Percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(cometbft_consensus_validator_power{chain_id=\"$chain_id\", instance=\"$instance\"}) / avg(cometbft_consensus_validators_power{chain_id=\"$chain_id\", instance=\"$instance\"}) * 100",
     "legendFormat": "Voting Power"
    }
   ]
  },
  {
   "title": "Late Votes per 1min",
   "type": "timeseries",
   "description": "The number of votes received by the node since startup that reference earlier block heights and consensus rounds than the node's current state.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "irate(cometbft_consensus_late_votes{chain_id=\"$chain_id\",instance=\"$instance\"}[1m])",
     "legendFormat": "{{vote_type}}"
    }
   ]
  },
  {
   "title": "Validator Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "cometbft_consensus_validator_power{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duplicate Vote Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "expr": "rate(cometbft_consensus_duplicate_vote{chain_id=\"$chain_id\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wallet Balance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "cosmos_validators_exporter_wallet_balance{chain=\"$chain\",host=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "targets": [
    {
     "expr": "cometbft_p2p_peers{chain_id=\"$chain_id\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "targets": [
    { "expression": "1-$A", "type": "math" }
   ]
  },
  {
   "title": "Mempool Active Outbound Connections",
   "type": "timeseries",
   "description": "Indicates the count of active outbound connections the node uses to distribute transactions via the gossip protocol.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cometbft_mempool_active_outbound_connections{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "targets": [
    {
     "expr": "cosmos_validators_exporter_active{chain=\"$chain\",host=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jiled",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "targets": [
    {
     "expr": "cosmos_validators_exporter_jailed{chain=\"$chain\",host=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Consensus Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 } },
  {
   "title": "Bonded Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "targets": [
    {
     "expr": "cosmos_validators_exporter_tokens_bonded_total{chain=\"$chain\",host=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Missing Validators",
   "type": "timeseries",
   "description": "Number of validators who did not sign",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
   "targets": [
    {
     "expr": "cometbft_consensus_missing_validators{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validators Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
   "targets": [
    {
     "expr": "cometbft_consensus_validators_power{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Processing Time Distribution",
   "type": "timeseries",
   "description": "This dashboard tracks the block processing time bucket, showing the total number of blocks that exceeded all defined processing time thresholds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(cometbft_state_block_processing_time_bucket{chain_id=\"$chain_id\", instance=\"$instance\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bad Validators Pct",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "(($A+$B)/$C)*100", "type": "math" }
   ]
  },
  {
   "title": "Queries success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 116 },
   "targets": [
    {
     "expr": "cosmos_validators_exporter_queries_success{chain=\"$chain\",host=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consensus txs [1m]",
   "type": "timeseries",
   "description": "Consensus txs per 1 min",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 124 },
   "targets": [
    {
     "expr": "delta(cometbft_consensus_total_txs{chain_id=\"$chain_id\", instance=\"$instance\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queries error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 124 },
   "targets": [
    {
     "expr": "cosmos_validators_exporter_queries_error{chain=\"$chain\",host=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queries total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 132 },
   "targets": [
    {
     "expr": "cosmos_validators_exporter_queries_total{chain=\"$chain\",host=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Chain Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 140 } },
  {
   "title": "Transactions Rate",
   "type": "timeseries",
   "description": "Transactions rate processed by the node across all blocks in the chain.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 141 },
   "targets": [
    {
     "expr": "rate(cometbft_consensus_total_txs{chain_id=\"$chain_id\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prevote Message Delay",
   "type": "timeseries",
   "description": "The time difference in seconds between the block proposal timestamp and the timestamp of the most recent prevote that reached quorum during the prevote step.\n",
   "gridPos": { "h": 40, "w": 12, "x": 12, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "cometbft_consensus_quorum_prevote_delay{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "{{proposer_address}}"
    }
   ]
  },
  {
   "title": "Mempool Recheck Rate",
   "type": "timeseries",
   "description": "Number of transactions rechecked in the mempool",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 149 },
   "targets": [
    {
     "expr": "rate(cometbft_mempool_recheck_times{chain_id=\"$chain_id\", instance=\"$instance\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Size",
   "type": "timeseries",
   "description": "The data size of the block in bytes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "cometbft_consensus_block_size_bytes{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mempool Tx",
   "type": "timeseries",
   "description": "Number of uncommitted transactions",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 165 },
   "targets": [
    {
     "expr": "cometbft_mempool_size{chain_id=\"$chain_id\", host=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uncommitted Txs",
   "type": "timeseries",
   "description": "The number of pending transactions currently in the mempool.\nAn increasing count may signal high network activity or delays in block production, while an empty mempool typically indicates low transaction volume.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 173 },
   "targets": [
    {
     "expr": "cometbft_mempool_size{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "System Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 181 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 182 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{host=\"$host\", mode=\"system\" }[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{host=\"$host\"}) by (cpu)))",
     "legendFormat": "System - Processes executing in kernel mode"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{host=\"$host\", mode=\"user\" }[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{host=\"$host\"}) by (cpu)))",
     "legendFormat": "User - Normal processes executing in user mode"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$instance\", mode=\"nice\" ,job=\"${job}\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$instance\" ,job=\"${job}\"}) by (cpu)))",
     "legendFormat": "Nice - Niced processes executing in user mode"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{host=\"$host\", mode=\"iowait\" }[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{host=\"$host\"}) by (cpu)))",
     "legendFormat": "Iowait - Waiting for I/O to complete"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{host=\"$host\", mode=\"irq\" }[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{host=\"$host\"}) by (cpu)))",
     "legendFormat": "Irq - Servicing interrupts"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{host=\"$host\", mode=\"softirq\" }[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{host=\"$host\"}) by (cpu)))",
     "legendFormat": "Softirq - Servicing softirqs"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{host=\"$host\", mode=\"steal\" }[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{host=\"$host\"}) by (cpu)))",
     "legendFormat": "Steal - Time spent in other operating systems when running in a virtualized environment"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{host=\"$host\", mode=\"idle\" }[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{host=\"$host\"}) by (cpu)))",
     "legendFormat": "Idle - Waiting for something to happen"
    }
   ]
  },
  {
   "title": "IOWait",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 182 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(node_pressure_io_waiting_seconds_total{host=\"$host\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{host=\"$host\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{host=\"$host\"} - node_memory_MemFree_bytes{host=\"$host\"} - (node_memory_Cached_bytes{host=\"$host\"} + node_memory_Buffers_bytes{host=\"$host\"} + node_memory_SReclaimable_bytes{host=\"$host\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{host=\"$host\"} + node_memory_Buffers_bytes{host=\"$host\"} + node_memory_SReclaimable_bytes{host=\"$host\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{host=\"$host\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{host=\"$host\"} - node_memory_SwapFree_bytes{host=\"$host\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Disk IOps Completed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{host=\"$host\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Reads completed"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{host=\"$host\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Writes completed"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 198 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{host=\"$host\"}[$__rate_interval])*8",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"$instance\" ,job=\"${job}\"}[$__rate_interval])*8",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "Disk R/W Data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 198 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{host=\"$host\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Read bytes"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{host=\"$host\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Written bytes"
    }
   ]
  },
  {
   "title": "Memory Writeback and Dirty",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 206 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_Writeback_bytes{host=\"$host\"}",
     "legendFormat": "Writeback - Memory which is actively being written back to disk"
    },
    {
     "expr": "node_memory_WritebackTmp_bytes{host=\"$host\"}",
     "legendFormat": "WritebackTmp - Memory used by FUSE for temporary writeback buffers"
    },
    {
     "expr": "node_memory_Dirty_bytes{host=\"$host\"}",
     "legendFormat": "Dirty - Memory which is waiting to get written back to the disk"
    }
   ]
  },
  {
   "title": "Disk Average Wait Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 206 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{host=\"$host\"}[$__rate_interval]) / irate(node_disk_reads_completed_total{host=\"$host\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Read wait time avg"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{host=\"$host\"}[$__rate_interval]) / irate(node_disk_writes_completed_total{host=\"$host\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Write wait time avg"
    }
   ]
  },
  {
   "title": "Network Errors [1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 214 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "delta(node_network_receive_errs_total{host=\"$host\"}[1m])",
     "legendFormat": "{{device}} - Receive errors"
    },
    {
     "expr": "delta(node_network_transmit_errs_total{host=\"$host\"}[1m])",
     "legendFormat": "{{device}} - Transmit errors"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 214 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{host=\"$host\"} * 100) / node_filesystem_size_bytes{host=\"$host\"})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  }
 ]
}